services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file: ./secrets/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app
  
  app:
    build: ./app
    container_name: app
    restart: always
    env_file: ./secrets/app.env
    networks:
      - app
    depends_on:
      - postgres
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets/certs:/etc/nginx/certs:ro
    networks:
      - app
    ports:
      - "443:443"
    depends_on:
      - app  

networks:
  app:
    driver: bridge