services:
  # Обратный прокси
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./services/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets/certs:/etc/nginx/certs:ro
    networks:
      - app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kraineff
      - faithful
  
  # База данных
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    env_file: ./secrets/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./services/postgres.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - database
  
  # kraineff.com
  kraineff:
    build: ./services/kraineff
    container_name: kraineff
    restart: always
    env_file: ./secrets/kraineff.env
    networks:
      - app
      - database
    depends_on:
      - postgres
  
  # faithful.team
  faithful:
    build: ./services/faithful
    container_name: faithful
    restart: always
    env_file: ./secrets/faithful.env
    networks:
      - app

volumes:
  postgres:

networks:
  app:
    driver: bridge
  database:
    driver: bridge