services:
  app:
    build: ./app
    container_name: app
    restart: always
    env_file: ./secrets/app.env
    networks:
      - app
    extra_hosts:
      - "database:192.168.0.5"
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets/certs:/etc/nginx/certs:ro
    ports:
      - "443:443"
    networks:
      - app
    depends_on:
      - app

networks:
  app:
    driver: bridge