services:
  app:
    build: ./app
    container_name: app
    restart: always
    env_file: "app.env"
    networks:
      - app_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "443:443"
    networks:
      - app_network
    depends_on:
      - app
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.2"

networks:
  app_network:
    driver: bridge